# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from test import hellogRPC_pb2 as hellogRPC__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/hellogRPC.Greeter/SayHello',
        request_serializer=hellogRPC__pb2.HelloRequest.SerializeToString,
        response_deserializer=hellogRPC__pb2.HelloReply.FromString,
        )
    self.SayGoodbye = channel.unary_unary(
        '/hellogRPC.Greeter/SayGoodbye',
        request_serializer=hellogRPC__pb2.GoodbyeRequest.SerializeToString,
        response_deserializer=hellogRPC__pb2.GoodbyeResponse.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayGoodbye(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=hellogRPC__pb2.HelloRequest.FromString,
          response_serializer=hellogRPC__pb2.HelloReply.SerializeToString,
      ),
      'SayGoodbye': grpc.unary_unary_rpc_method_handler(
          servicer.SayGoodbye,
          request_deserializer=hellogRPC__pb2.GoodbyeRequest.FromString,
          response_serializer=hellogRPC__pb2.GoodbyeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hellogRPC.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
