# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
        - name: server
          image: ericwudocker01/grpc:frontend
          ports:
          - name: http
            containerPort: 5000
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthz
              port: 5000
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthz
              port: 5000
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          env:
          - name: PORT
            value: "5000"
          - name: REGISTER_SERVICE_ADDR
            value: "register:50051"
          - name: LOGIN_SERVICE_ADDR
            value: "login:50052"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external1
spec:
  type: LoadBalancer
  selector:
    app: frontend1
  ports:
  - name: http
    port: 1233
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
        - name: server
          image: ericwudocker01/grpc:register
          ports:
          - name: http
            containerPort: 50051
          readinessProbe:
            initialDelaySeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: register
spec:
  type: ClusterIP
  selector:
    app: register
  ports:
  - name: http
    port: 50051
    targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: server
          image: ericwudocker01/grpc:login
          ports:
          - name: http
            containerPort: 50052
          readinessProbe:
            initialDelaySeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50052"]
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50052"]

---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  type: ClusterIP
  selector:
    app: login
  ports:
  - name: http
    port: 50052
    targetPort: 50052
---