version: "2"
services:

  db_mysql:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld01
    volumes:
      - .:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080